### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by tatsujb** [gajus/babel-plugin-react-css-modules#152]
The demo : [https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo](https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo)

does not run

```
PS test-project\babel-plugin-react-css-modules\demo> npm run
Lifecycle scripts included in :
  start
    webpack-dev-server
PS test-project\babel-plugin-react-css-modules\demo> npm start

> @ start test-project\babel-plugin-react-css-modules\demo
> webpack-dev-server

module.js:540
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (test-project\babel-plugin-react-css-modules\demo\node_modules
\webpack-dev-server\lib\Server.js:22:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2018-01-25T10_10_03_099Z-debug.log
```
Here's the log in question : 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;\WebstormProjects\test-project\babel-plugin-react-css-modules\demo\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;%JAVA_HOME%\bin;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;\AppData\Local\Microsoft\WindowsApps;C:\gradle-4.1\bin;C:\Program Files\Java\jdk1.8.0_144\bin;\AppData\Roaming\npm;\AppData\Local\Yarn\bin
9 verbose lifecycle @~start: CWD: \test-project\babel-plugin-react-css-modules\demo
10 silly lifecycle @~start: Args: [ '/d /s /c', 'webpack-dev-server' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `webpack-dev-server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd \test-project\babel-plugin-react-css-modules\demo
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `webpack-dev-server`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I followed your instructions to the letter which, by the way, do not work typing "webpack-dev-server" alone can't work. you should replace that line with "npm start".

there's probably a breakage caused by package versions changing.

**Comment by gajus** [comment]
> Error: Cannot find module 'webpack'

Looks like you don't have webpack installed.

**Comment by tatsujb** [comment]
what? you're supplying a demo here : https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo are you not? 

this demo includes a webpack.config.js, found here : https://github.com/gajus/babel-plugin-react-css-modules/blob/master/demo/webpack.config.js

and we run npm install as par of the use instructions.

how in the hell can you tell me I don't have webpack installed? it's your demo. you're the one who doens't have webpack installed.

If I'm missing something here, please, I'd like further instructions. 

forgive me for thinking this but as-is your demo doesn't run. and it's not my fault.
