### ISSUE TITLE
custom attribute mapping error

### ISSUE THREAD

**Issue by TITAN9389** [gajus/babel-plugin-react-css-modules#174]
i've tried many ways but always getting this error while adding custom attribute into my babel config 

`"attributeNames": { "activeStyleName": "activeClassName" }`

```
Error: Module build failed: Error: /Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/src/index.js: Invalid configuration
    at PluginPass.Program (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-plugin-react-css-modules/dist/index.js:204:17)
    at newFn (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/sebmaz/Desktop/WorkSpace/ReactJS/boilerplate-v4/node_modules/babel-traverse/lib/index.js:79:12)
```

here is my babelrc: 
```
{
	"presets": ["env", "react"],
	"plugins": [
		[
			"react-css-modules",
			{
				"handleMissingStyleName": "warn",
				"filetypes": {
					".scss": {
						"syntax": "postcss-scss"
					}
				},
				"attributeNames": { "styleName": "somethingOther" }
			}
		],
		"transform-class-properties",
		"transform-object-rest-spread",
		"transform-async-to-generator"
	]
}
```
everything works when i remove the "attributeNames".

**Comment by gajus** [comment]
Based on just the provided information, it should work. Your input matches the configuration schema.

https://github.com/gajus/babel-plugin-react-css-modules/blob/e5b2d955838fd65270ff435a72863f36df8c3b87/src/schemas/optionsSchema.json#L50-L65

Please try to inspect the source code to identify whats causing the error.

**Comment by sundeep-babbur** [comment]
The `optionsSchema.json` in the npm installed version of the plugin is not up to date with [this](babel-plugin-react-css-modules/src/schemas/optionsSchema.json) version and does not have any schema defined for `attributeNames`. So the plugin is throwing errors when `attributeNames` is defined.

@TITAN9389  as a temporary fix you can paste [this](babel-plugin-react-css-modules/src/schemas/optionsSchema.json) in your local schema file located in your project folder at `node_modules/babel-plugin-react-css-modules/dist/schemas/optionsSchema.json`.

I hope this will be fixed soon.

**Comment by BerkeleyTrue** [comment]
@sundeep-babbur I've tried your fix with no luck I'm still getting the same error.
