### ISSUE TITLE
webpack+babel+typescript Module build failed: TypeError Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by diegolaciar** [gajus/babel-plugin-react-css-modules#28]
My config is: typescript+babel loaders with webpack.
I added the plugin to `.babelrc`
I'm importing css file as 

```
import "./../../App.css";
```

And get this error:

```
ERROR in ./src/client/Streaming/components/Share/index.tsx
Module build failed: TypeError: /Users/diegolaciar/workspace/collide-react-web/src/client/Streaming/components/Share/index.tsx: Cannot read property 'replace' of undefined
    at generate (/Users/diegolaciar/workspace/collide-react-web/node_modules/generic-names/index.js:29:23)
    at exportScopedName (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:48:24)
    at localizeNode (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:64:28)
    at Array.map (native)
    at localizeNode (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:60:38)
    at traverseNode (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:78:20)
    at Array.map (native)
    at traverseNode (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at Array.map (native)
    at traverseNode (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:84:38)
    at /Users/diegolaciar/workspace/collide-react-web/node_modules/postcss-modules-scope/lib/index.js:103:25
    at /Users/diegolaciar/workspace/collide-react-web/node_modules/postcss/lib/container.js:241:28
    at /Users/diegolaciar/workspace/collide-react-web/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/Users/diegolaciar/workspace/collide-react-web/node_modules/postcss/lib/container.js:239:25)
 @ ./src/client/Streaming/App.tsx 34:13-42
```

thanks,

**Comment by notgiorgi** [comment]
Check this out: https://github.com/gajus/babel-plugin-react-css-modules/issues/4

**Comment by gajus** [comment]
> Cannot read property 'replace' of undefined

This issue has been fixed.
