### ISSUE TITLE
Cannot get server-side rendering without webpack to work

### ISSUE THREAD

**Issue by levity** [gajus/babel-plugin-react-css-modules#69]
I have created a fork (see #68) with the basic setup that should be necessary to get this plugin to work in a server-side rendering environment without webpack, e.g. with `renderToString`. The plugin does get run, but then throws this error:

```
❯ npm run -s server-example
/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/lawrence/Code/babel-plugin-react-css-modules/demo/src/components/table.css: Unexpected token (1:0)
> 1 | .table {
    | ^
  2 |   display: table;
  3 | }
  4 |
    at Parser.pp$5.raise (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:1716:8)
    at Parser.pp$3.parseExprAtom (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:3683:12)
    at Parser.parseExprAtom (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:7016:22)
    at Parser.pp$3.parseExprSubscripts (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:3427:19)
    at Parser.pp$3.parseMaybeUnary (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:3407:19)
    at Parser.pp$3.parseExprOps (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:3337:19)
    at Parser.pp$3.parseMaybeConditional (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:3314:19)
    at Parser.pp$3.parseMaybeAssign (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:3277:19)
    at Parser.parseMaybeAssign (/Users/lawrence/Code/babel-plugin-react-css-modules/demo/node_modules/babylon/lib/index.js:6242:20)
```

Am I misunderstanding how to use this plugin? Any help you can offer is greatly appreciated!

**Comment by levity** [comment]
I think I see where I misunderstood -- this plugin handles transforming `styleName` into `className` but it does not actually handle the requiring of CSS files. How can I accomplish that without webpack?

**Comment by gajus** [comment]
> Do you have any suggestions as to how can I accomplish that without webpack?

How are you intending to generate/ load CSS?

**Comment by levity** [comment]
I use webpack in my build step to generate static JS and CSS assets. But I don't want my web server code to depend upon webpack.

**Comment by gajus** [comment]
> but it does not actually handle the requiring of CSS files.

All this plugin does is gives components `className` that maps to the class names of the assets that you've generated statically using webpack.

**Comment by levity** [comment]
Yes, I understand; I was just asking if you know of any non-webpack options for generating the assets. I've come across one, `css-modules-require-hook`. Anyway, thanks for your help.
