### ISSUE TITLE
Errors while compiling. Reload prevented.

### ISSUE THREAD

**Issue by craigcosmo** [gajus/babel-plugin-react-css-modules#73]
error message:

```
./app/component/checkout/CheckoutView.js
Module build failed: Error: /Users/craigcosmo/Desktop/glorgo/app/component/checkout/CheckoutView.js: Could not resolve the styleName 'cart'.
    at styleNameValue.split.filter.map.styleName (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-plugin-react-css-modules/src/getClassName.js:59:15)
    at Array.map (native)
    at exports.default (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-plugin-react-css-modules/src/getClassName.js:43:6)
    at exports.default (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-plugin-react-css-modules/src/resolveStringLiteral.js:24:29)
    at PluginPass.JSXElement (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-plugin-react-css-modules/src/index.js:156:11)
    at newFn (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/craigcosmo/Desktop/glorgo/node_modules/babel-traverse/lib/context.js:190:19)
 @ ./app/index.js 41:20-64
 @ multi (webpack)-dev-server/client?http://localhost:1111 ./app/index.js
errors @ client?31fb:119
sock.onmessage @ socket.js:37
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
SockJS._transportMessage @ main.js:272
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
```

reproduce:

1. Create a component
2. Create a div inside component
3. Create a css file and import it to our newly created component
3. Now back to our component, add any stylename to the div, ex: `<div stylename="quick-style"></div>`
4. Press save. you will see the error
6. Now we know that we don't have that `.quick-style` declared in our css file. That's why the error. We will go to the css file and declare that `.quick-style {}`
7. Press save. The error still persists.

One way to get out of this error is restart the dev server.

**Comment by gajus** [comment]
It says clearly in the error whats the problem.

**Comment by craigcosmo** [comment]
when trying to fix the problem, it will be still there.

**Comment by samouss** [comment]
Hi, 

I' encountering the same problem.
I need to go back to my component and press save to enable the reload and the fix the error.
Save the CSS file should be enough to fix the problem no ?
